### ISSUE TITLE
Requirements regarding directory naming

### ISSUE THREAD

**Issue by M3ssman** [OCR-D/gt-repo-template#1]
# Description

Currently, it is not clear to the user, whether the name `GT-PAGE` for the directory containing the groundtruth data is a hard and fixed requirement. It seems to be; therefore using a different label should yield an error instead of having [an action running green](https://github.com/M3ssman/gt-test/actions/runs/6234047201).

**Comment by tboenig** [comment]
Hello @M3ssman

thank you very much for the comment.
Yes, it is correct that the structure is mandatory. The folders `date`; `GT-PAGE` are mandatory. See also the `readme file` for the repo template.
The workflow is now optimized.
It now has a UniTest that analyzes the folder structure. 
1. it checks if the folders `data` or `GT-PAGE` are present.
2. it checks if the structure of the folders is also correct.

Only if these two conditions are fulfilled, the workflow continues with the analysis of the PAGE files.
