### ISSUE TITLE
Alert invalid data layout

### ISSUE THREAD

**Issue by M3ssman** [OCR-D/gt-repo-template#4]
# Description

It is required to hold data in a directory layout with the subfolder `GT-PAGE` straight beneath the directory which contains the `mets.xml`. 

Currently, if this layout is not matched, the workflow creates a rather empty bagit-file without any data and an empty `mets.xml`. 
Instead of behaving like this, it would be better to signal the invalid layout and make the workflow yield the error.

**Comment by tboenig** [comment]
The workflow step: ``uniTest`` checks whether the data structure is correct.
If it is not, an error message is issued in the step: uniTestError, which lists the corresponding directory/error.
If there is no error, no error is reported, the workflow runs through and the analyze_and_makebagit workflow follows.

regards tboenig
