### ISSUE TITLE
"File not found" error in gtrepo action

### ISSUE THREAD

**Issue by maxte0** [OCR-D/gt-repo-template#6]
In the analyse_and_makebagit  part of the gtrepo action we encountered a missing file error during the DHd workshop. 

The problem was resolved by substituting the METADATA.yml for another one known to be working. Below are the error message and the (probably faulty) METADATA.yml (as txt, yml wasn't allowed), which was generated through the suggested form at https://tboenig.github.io/gt-metadata/document-your-gt.html .

See action under: https://github.com/maxte0/ocr_trainingsdaten/actions/runs/8067064928/job/22036618726
![image](https://github.com/OCR-D/gt-repo-template/assets/161472118/6456f415-789c-4f50-a80b-1ffa7a67d578)
[METADATA.txt](https://github.com/OCR-D/gt-repo-template/files/14422002/METADATA.txt)

**Comment by tboenig** [comment]
Hi @maxte0,

The "bug" has been fixed.
The specification document GT (see Type of Ground Truth) caused this behavior of the app.
![image](https://github.com/OCR-D/gt-repo-template/assets/26142921/678c9b4b-99a0-4a5c-ad0a-99d9a818234e)
Img: Screenshot from metadata form (https://tboenig.github.io/gt-metadata/document-your-gt.html)

To clarify. The option: document GT means that 
the ground truth contains annotated and **complete documents**. In your case, this would probably be a volume of the Gemein Nachrichten. 
I assume you did not want to offer the whole volume as a GT, but only part of it. The structure and text GT option would have been the better choice. Correct your Metadata.yml and restart your workflow with a new tag. The workflow should now run without errors.

all the best
tboenig

**Comment by maxte0** [comment]
Thanks for looking into the issue. I should have paid closer attention when the GT types were introduced in the workshop!

**Comment by tboenig** [comment]
I spoke to @bertsky . Originally, a differentiation was also planned for the naming of the directories according to the metadata. But that sometimes makes everything more complicated. For this reason, there is now only one standardized name for the directories. The metadata now contains information about the data (name, Git repo...) or GT types. This is of course also the task of the metadata.
